navbar: 
  logo: # choose [img] or [icon + title]
    img: https://pro.upload.logomaker.com.cn/temp24h/logo/417872f4-c905-464a-9150-8c0d2849d954.svg
    icon:
    title: 
  menu: 
    - name: 主页
      icon: fa-solid fa-rss
      url: /
    - name: 文章归档
      icon: fa-solid fa-archive
      rows: 
        - name: 分类
          icon: fa-solid fa-folder-open
          url: categories/
        - name: 标签
          icon: fa-solid fa-tags
          url: tags/
    - name: 友链
      icon: fa-solid fa-link
      url: friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
    - name: 日间/夜间模式 
      icon: fa-solid fa-sun # 我更喜欢太阳的小图标
      toggle: darkmode
cover:
  background: https://api.dujin.org/bing/1920.php  # 可以是任意的图片api，百度即可
  logo:
  title: '你汪哥'
  subtitle: '真实的个人，真实的生活，和真实的经验分享，感谢所有具有开源精神的人！'
  search: 搜你想搜
  features:
    - name: 首页
      icon: fa-solid fa-rss
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      img: volantis-static/media/twemoji/assets/svg/1f396.svg 
      url: /categories/
    - name: 标签
      icon: fa-solid fa-tags
      img: volantis-static/media/twemoji/assets/svg/1f389.svg 
      url: /tags/
    - name: 文章归档
      icon: fa-solid fa-archive
      img: volantis-static/media/twemoji/assets/svg/1f516.svg 
      url: /archives/
    - name: 友链
      icon: fa-solid fa-link
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg 
      url: /friends/
    - name: 关于
      icon: fa fa-code-branch
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg 
      url: about/
search:
  enable: true
  service: hexo
### 自定义右键 新
rightmenus:
  enable: true
  # 右键菜单项及加载顺序
  # 内容示例：plugins.[组名], menus.[组名], hr(分割线，推荐去线留白), music(音乐控制器)
  order: 
    - plugins.navigation
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    # - plugins.elementImage
    - menus.link
    - hr
    - menus.darkMode
    - plugins.articlePage
    - music
  # 基础项设置
  options:
    # 图标前缀 fa-solid, fa-regular, fa-light, fa-thin, fa-duotone, fa-brands
    iconPrefix: fa-solid
    # 例外，在 articlePage 组显示时（文章页）时依旧显示含 link 属性的菜单项
    articleShowLink: false
    # 当设定全局音乐播放器时，是否一直显示音乐控制菜单。false：仅当音乐播放时启用
    musicAlwaysShow: false
    # 适用于复制图片文件的场景，当图片源未设置 Access-Control-Allow-Origin 时，图片复制由于 CORS 问题失败
    # 你可以自行部署相应项目解决该问题，详见：https://github.com/Rob--W/cors-anywhere 或者 https://github.com/Zibri/cloudflare-cors-anywhere
    corsAnywhere: 
  # 右键内置组，预置实现
  plugins:
    # 导航组件
    # 横向排列，共用一行，仅显示图标 (原则上支持的数量不限)
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-solid fa-arrow-left', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-solid fa-arrow-right', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-solid fa-redo', event: 'window.location.reload()', group: 'navigation'}
      #- {id: 'up', name: '回到顶部', icon: 'fa-solid fa-arrow-up', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation'}
      - {id: 'home', name: '回到首页', icon: 'fa-solid fa-home', link: '/', group: 'navigation'}
    # 文本输入框相关组件
    # 生效于 input/textarea，粘贴、剪切、全选
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-solid fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-solid fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-solid fa-cut', event: 'copyCut', group: 'inputBox'}
    # 文本选中类组件
    # 生效于右键选中文本，__text__ 为选中的文本。     
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-solid fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-solid fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'CSDNSearch', name: 'CSDN搜索', icon: 'fa-solid fa-search', event: 'window.open(`https://so.csdn.net/so/search?q=${__text__}`)', group: 'seletctText'}
      - {id: 'baiduSearch', name: '百度搜索', icon: 'fa-solid fa-search', event: 'window.open(`https://www.baidu.com/s?wd=${__text__}`)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-solid fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
      # - {id: 'googleSearch', name: '谷歌搜索', icon: 'fa-solid fa-search', event: 'window.open(`https://www.google.com/search?q=${__text__}`)', group: 'seletctText'}
    # 链接判断组件
    # 生效于链接处的右键行为，__link__ 为链接地址
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-solid fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-solid fa-link', event: 'copyLink', group: 'elementCheck'}
    # 图片判断类组件
    # 生效于图片类的右键行为，__link__ 为链接地址
    # elementImage:
      # - {id: 'copyImg', name: '复制图片', icon: 'fa-solid fa-image', event: 'copyImg', group: 'elementImage'}
      # - {id: 'googleImg', name: '谷歌识图', icon: 'fa-solid fa-images', event: 'window.open(`https://www.google.com.hk/searchbyimage?image_url=${__link__}`)', group: 'elementImage'}
    # 文章页面组件
    # 生效于 post.article 页面
    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-solid fa-print', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-solid fa-book-open', event: 'readMode', group: 'articlePage'}
  # 右键自定义菜单区域
  menus:
    link:
      - {id: 'help', name: '常见问题', icon: 'fa-solid fa-question', link: 'https://volantis.js.org/faqs/', group: 'link'}
      - {id: 'examples', name: '示例博客', icon: 'fa-solid fa-rss', link: 'https://volantis.js.org/examples/', group: 'link'}
      # - {id: 'contributors', name: '加入社区', icon: 'fa-solid fa-fan', link: 'https://volantis.js.org/contributors/', group: 'link'}
      # - hr
      - {id: 'source_docs', name: '本站源码', icon: 'fa-solid fa-code-branch', link: 'https://github.com/xiaobai54188/xiaobai54188.github.io', group: 'link'}
      - {id: 'source_theme', name: 'volantis社区', icon: 'fa-solid fa-code-branch', link: 'https://volantis.js.org/', group: 'link'}
    darkMode: 
     - {id: 'darkMode', name: '夜间模式', icon: 'fa-solid fa-moon', event: 'volantis.dark.toggle()', group: 'darkMode'}
###
plugins:
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 300            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://pic.imgdb.cn/item/63ca552dbe43e0d30ea6ba65.jpg
      # 此处添加你想设置的壁纸或者壁纸API
  darkmode:
    enable: true
custom_css:
  navbar:
    height: 64px
    width: auto # auto, max
    effect: [shadow, blur] # [shadow, floatable, blur]
  scrollbar:
    size: 4px
    border: 2px
    color: "#2196f3"
    hover: "#ff5722"
  fontfamily:
    logofont:
      fontfamily: 'Wangyan'
      name: 'Wangyan'
      url: https://cdn.jsdelivr.net/gh/inkss/common@1/fonts/canva/HYRunYuan.woff2     
      weight: normal
      style: normal
comments:
  service: giscus
  giscus:
    repo: "xiaobai54188/xiaobai54188.github.io"
    repo-id: "R_kgDOIy_sVA"
    category: "General"
    category-id: "DIC_kwDOIy_sVM4CTqQU"
    lang: "zh-CN"
    theme:
      light: "light" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css
sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://pro.upload.logomaker.com.cn/temp24h/logo/417872f4-c905-464a-9150-8c0d2849d954.svg # 这里放置你的logo地址
      shape: rectangle # circle, rectangle
      url: /about/
      title: 
      subtitle:
      jinrishici: True # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: 
        - icon: fab fa-github
          url: https://github.com/xiaobai54188
        - icon: fa fa-comments
          url: https://qm.qq.com/cgi-bin/qm/qr?k=YDxnDZsXWxHY7TcNnJjgwg5nO57P76Ur&noverify=0   
# 文章布局
article:
  # 文章详情页面的文章卡片本体布局方案
  body:
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://pro.upload.logomaker.com.cn/temp24h/logo/417872f4-c905-464a-9150-8c0d2849d954.svg
        name: wang
        url: /
      tags:
        icon: fas fa-hashtag
      # 分享
      share:
        - id: qq
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 版权声明组件 (for layout: post/docs)
      copyright:
        enable: true
        # permalink: '本文永久链接是：'
        content:
          - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          # - permalink
      # ----------------
    # meta library
    # ---------------------------------------
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-envelope
      url: wangyan20090214@qq.com
    - icon: fab fa-github
      url: https://github.com/xiaobai54188
    - icon: fa fa-comments
      url: https://qm.qq.com/cgi-bin/qm/qr?k=YDxnDZsXWxHY7TcNnJjgwg5nO57P76Ur&noverify=0
  copyright: "[Copyright © 2017-2023 wangyan](/)"
  br: "
<br>"
